# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8098
  connection-timeout: 5000ms
  servlet:
    context-path: /fagaiwei_api

spring:
  # 环境 dev|test|prod
  profiles:
#    active: dev
    active: prod
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

app:
  path:
    work-dir: /zhjg/app/fagaiwei_app
    userDir: /zhjg/app/fagaiwei_app
    module:   ##${user.dir}/ 把他去掉
      report: /zhjg/app/fagaiwei_app/report
      reportResult: /zhjg/app/fagaiwei_app/reportResult
    temp: /temp
    upload: /upload

#启用CA登录配置
ca:
  valid: true

rsp-server:
  url: sp.ndrc.gov.cn

bim:
  key: 123456
  type: AES
