DROP PROCEDURE IF EXISTS CREATE_USER;
DELIMITER //
CREATE PROCEDURE CREATE_USER(
   IN P_USER_ID VARCHAR(50)
	 ,IN P_DEP_ID VARCHAR(50)
	 ,IN P_USER_NAME VARCHAR(60)
	 ,IN P_USER_RELA_NAME VARCHAR(100)
	 ,IN P_MBL_PHONE_NO VARCHAR(100)
	 ,IN P_USER_PASS VARCHAR(60)
	 ,IN P_EMAIL VARCHAR(80)
   ,IN P_USER_STATUS INT
	 ,IN ROLES VARCHAR(200)
	 ,OUT ERROR_NO INT
	 )
	 BEGIN
	 DECLARE IDX INT;
	 DECLARE P_ROLE_ID VARCHAR(16);
	 DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET ERROR_NO = 0;
	 SET ERROR_NO = 1;

	 START TRANSACTION;

	 INSERT INTO pss_user_info(
	 user_id ,
	 user_pass,
	 user_name,
	 user_real_name,
	 mbl_phone_no,
	 email,
	 user_status,
	 crte_date,
	 upd_date
	 )
	 VALUES(
	 P_USER_ID,
	 P_USER_PASS,
	 P_USER_NAME,
	 P_USER_RELA_NAME,
	 P_MBL_PHONE_NO,
	 P_EMAIL,
	 P_USER_STATUS,
	 CURRENT_TIMESTAMP ,
	CURRENT_TIMESTAMP
	 );

	 DELETE  FROM pss_user_dep_rela WHERE user_id = P_USER_ID;

   INSERT INTO pss_user_dep_rela(
	 user_id,
	 dep_id
	 )VALUES(
	 P_USER_ID,
	 P_DEP_ID
	 );

	 DELETE  FROM pss_user_role_rela WHERE user_id = P_USER_ID ;

	 SET IDX = LOCATE(',',ROLES);

	 IF IDX = 0 AND LENGTH(ROLES)>0 THEN
	      SET IDX = LENGTH(ROLES)+1;
	 END IF;

	 WHILE IDX > 0
	 DO
	    SET P_ROLE_ID = LEFT(ROLES,IDX-1);
	 INSERT INTO pss_user_role_rela(
	   user_id
		 ,role_id
		 ,cre_date
		 ,upd_date
	 )
	 VALUES(
	  P_USER_ID
		,P_ROLE_ID
		,CURRENT_TIMESTAMP
		,CURRENT_TIMESTAMP
	 );

   SET ROLES = SUBSTR(ROLES FROM IDX+1);
   SET IDX = LOCATE(',',ROLES);

   IF IDX = 0 AND LENGTH(ROLES)>0 THEN
	    SET IDX = LENGTH(ROLES)+1;
	 END IF;

END WHILE;

   IF ERROR_NO = 0 THEN
	    ROLLBACK;
	 ELSE
	    COMMIT;
		END IF;

END //